name: Build CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: apt-get install
      run: sudo apt-get install libpam-dev
    - name: autoreconf
      run: autoreconf --install
    - name: configure
      run: ./configure CFLAGS='-g -O2 -Wall -Werror -Wextra'
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
